image: node:16.14.2
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@7.1.2
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - gh-pages
    - pages